awscli:
  update: true
  gpg_key:
    url: 'https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html'
    hash:
      sha512: '2f85eb35b7b63eb435b4437d019b0db9a742d9d9c7a13f241a64b650c51e2e1b3a88460ece4a4abeeb123cf2df96274a0045e93559c973d5874ad884feef9951'
    storage:
      raw: /opt/aws/cli/awscli.gpg.asc
      keyring: /opt/aws/cli/awscli.gpg
  archive:
    url: 'https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip'
    signature: 'https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip.sig'
  storage:
    prefix: /opt/aws/cli
