- name: Symlink vte
  file:
    state: link
    path: /etc/profile.d/vte.sh
    src: /etc/profile.d/vte-2.91.sh
    owner: root
    group: root
    mode: u=rwx,go=rx

- name: Setup vte for Tilix
  blockinfile:
    path: "/home/{{ primary_username }}/.bashrc"
    marker: "# {mark} Tilix Config"
    block: |
      if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
        source /etc/profile.d/vte.sh
      fi

- name: Configure Tilix
  become: true
  become_user: "{{ primary_username }}"
  dconf:
    key: "/com/gexperts/Tilix/{{ item.key }}"
    value: "{{ item.value }}"
  with_dict:
    middle-click-close: 'true'
    control-scroll-zoom: 'true'
    copy-on-select: 'true'
    window-style: "'disable-csd'"
    terminal-title-style: "'small'"
    theme-variant: "'dark'"

- name: Configure Tilix Profile
  become: true
  become_user: "{{ primary_username }}"
  dconf:
    key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/{{ item.key }}"
    value: "{{ item.value }}"
  with_dict:
    # Material
    background-color: "'#263238'"
    badge-color-set: 'false'
    bold-color-set: 'false'
    cursor-colors-set: 'false'
    foreground-color: "'#A1B0B8'"
    highlight-colors-set: 'false'
    palette: "['#252525', '#FF5252', '#C3D82C', '#FFC135', '#42A5F5', '#D81B60', '#00ACC1', '#F5F5F5', '#708284', '#FF5252', '#C3D82C', '#FFC135', '#42A5F5', '#D81B60', '#00ACC1', '#F5F5F5']"
    scrollback-lines: 81920
    use-theme-colors: 'false'

- name: Fix conflict with the default show desktop hotkey 
  become: true
  become_user: "{{ primary_username }}"
  dconf:
    key: /org/gnome/desktop/wm/keybindings/show-desktop
    value: "['<Primary><Super>d', '<Super>d']"

- name: Set Tilix as default Terminal
  alternatives:
    name: x-terminal-emulator
    path: /usr/bin/tilix.wrapper
